name: Continuous Integration (CI) 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install-deps
      run: sudo apt-get install libreadline-dev -y
    - name: make
      run: make
    - name: make check
      run: make check
